#!/bin/bash
ulimit -n ULIMIT
source config.sh
echo "python client_connection.py $CLIENT_IP_FIRST $CLIENT_IP_END $CLIENT_IP_PREFIX $SERVER_IP_FIRST $SERVER_IP_END $SERVER_IP_PREFIX $SERVER_PORT $CONNECTION_MAX"
python client_connection.py $CLIENT_IP_FIRST $CLIENT_IP_END $CLIENT_IP_PREFIX $SERVER_IP_FIRST $SERVER_IP_END $SERVER_IP_PREFIX $SERVER_PORT $CONNECTION_MAX
