#!/bin/bash
ulimit -n ULIMIT
source config.sh
echo "python client_connection.py $CLIENT_IP_FIRST $CLIENT_IP_END $CLIENT_IP_PREFIX $PUB_IP_MID_FIRST $PUB_IP_MID_END $SERVER_IP_PREFIX $SERVER_PORT $CONNECTION_MAX"
python client_connection.py $CLIENT_IP_FIRST $CLIENT_IP_END $CLIENT_IP_PREFIX31. $PUB_IP_MID_FIRST $PUB_IP_MID_END $SERVER_IP_PREFIX $SERVER_PORT $CONNECTION_MAX
